### ISSUE TITLE
Why is endless loop required

### ISSUE THREAD

**Issue by khokm** [badcf00d/UEFI-helloworld#1]
Hello!
Sorry for be curious, but why is endless loop required at the end of efi program?
https://github.com/badcf00d/UEFI-helloworld/blob/a0344c970df5296c6c1e965ad1290b2bc5ba5568/src/uefi.asm#L26
If we remove it, the computer will halt? Or something else happens?

**Comment by badcf00d** [comment]
It's not really "required", It's been a while since I wrote this, but from memory I think it's just useful to keep the hello world text on screen. Otherwise the program exists immediately and you never see the output... or something like that
